In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf

In [2]:
sentences = [
    'My favorite food is ice cream',
    'do you like ice cream too?',
    'My dog likes ice cream!',
    "your favorite flavor of icecream is chocolate",
    "chocolate isn't good for dogs",
    "your dog, your cat, and your parrot prefer broccoli"
]

In [3]:
# Optionally set the max number of words to tokenize.
# The out of vocabulary (OOV) token represents words that are not in the index.
# Call fit_on_text() on the tokenizer to generate unique numbers for each word
tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)

In [4]:
# Examine the word index
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'your': 2, 'ice': 3, 'cream': 4, 'my': 5, 'favorite': 6, 'is': 7, 'dog': 8, 'chocolate': 9, 'food': 10, 'do': 11, 'you': 12, 'like': 13, 'too': 14, 'likes': 15, 'flavor': 16, 'of': 17, 'icecream': 18, "isn't": 19, 'good': 20, 'for': 21, 'dogs': 22, 'cat': 23, 'and': 24, 'parrot': 25, 'prefer': 26, 'broccoli': 27}


In [5]:
# Get the number for a given word
print(word_index['favorite'])

6


In [6]:
sequences = tokenizer.texts_to_sequences(sentences)
print (sequences)

[[5, 6, 10, 7, 3, 4], [11, 12, 13, 3, 4, 14], [5, 8, 15, 3, 4], [2, 6, 16, 17, 18, 7, 9], [9, 19, 20, 21, 22], [2, 8, 2, 23, 24, 2, 25, 26, 27]]


In [9]:
padded = pad_sequences(sequences)
print('\nWord Index = ', word_index)
print('\nSequences = ', sequences)
print('\nPadded Sequences:')
print(padded)


Word Index =  {'<OOV>': 1, 'your': 2, 'ice': 3, 'cream': 4, 'my': 5, 'favorite': 6, 'is': 7, 'dog': 8, 'chocolate': 9, 'food': 10, 'do': 11, 'you': 12, 'like': 13, 'too': 14, 'likes': 15, 'flavor': 16, 'of': 17, 'icecream': 18, "isn't": 19, 'good': 20, 'for': 21, 'dogs': 22, 'cat': 23, 'and': 24, 'parrot': 25, 'prefer': 26, 'broccoli': 27}

Sequences =  [[5, 6, 10, 7, 3, 4], [11, 12, 13, 3, 4, 14], [5, 8, 15, 3, 4], [2, 6, 16, 17, 18, 7, 9], [9, 19, 20, 21, 22], [2, 8, 2, 23, 24, 2, 25, 26, 27]]

Padded Sequences:
[[ 0  0  0  5  6 10  7  3  4]
 [ 0  0  0 11 12 13  3  4 14]
 [ 0  0  0  0  5  8 15  3  4]
 [ 0  0  2  6 16 17 18  7  9]
 [ 0  0  0  0  9 19 20 21 22]
 [ 2  8  2 23 24  2 25 26 27]]


In [10]:
padded = pad_sequences(sequences, maxlen=15, padding='post')

print('\nPadded Sequences:')
print(padded)


Padded Sequences:
[[ 5  6 10  7  3  4  0  0  0  0  0  0  0  0  0]
 [11 12 13  3  4 14  0  0  0  0  0  0  0  0  0]
 [ 5  8 15  3  4  0  0  0  0  0  0  0  0  0  0]
 [ 2  6 16 17 18  7  9  0  0  0  0  0  0  0  0]
 [ 9 19 20 21 22  0  0  0  0  0  0  0  0  0  0]
 [ 2  8  2 23 24  2 25 26 27  0  0  0  0  0  0]]


In [11]:
padded = pad_sequences(sequences, maxlen=3, padding='post')

print('\nPadded Sequences:')
print(padded)


Padded Sequences:
[[ 7  3  4]
 [ 3  4 14]
 [15  3  4]
 [18  7  9]
 [20 21 22]
 [25 26 27]]


In [12]:
test_data = [
    "my best friend's favorite ice cream flavor is strawberry",
    "my dog's best friend is a manatee"
]
print (test_data)

# Remind ourselves which number corresponds to the
# out of vocabulary token in the word index
print("<OOV> has the number", word_index['<OOV>'], "in the word index.")

# Convert the test sentences to sequences
test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

# Pad the new sequences
padded = pad_sequences(test_seq, maxlen=10)
print("\nPadded Test Sequence: ")

# Notice that "1" appears in the sequence wherever there's a word 
# that's not in the word index
print(padded)

["my best friend's favorite ice cream flavor is strawberry", "my dog's best friend is a manatee"]
<OOV> has the number 1 in the word index.

Test Sequence =  [[5, 1, 1, 6, 3, 4, 16, 7, 1], [5, 1, 1, 1, 7, 1, 1]]

Padded Test Sequence: 
[[ 0  5  1  1  6  3  4 16  7  1]
 [ 0  0  0  5  1  1  1  7  1  1]]


In [15]:
path = tf.keras.utils.get_file('reviews.csv', 'https://drive.google.com/uc?id=13ySLC_ue6Umt9RJYSeM2t-V0kCv-4C-P')
print (path)

127831/127831 [==============================] - 0s 0us/step
C:\Users\Администратор.SHTAUF\.keras\datasets\reviews.csv


In [60]:
import pandas as pd
import numpy as np
keras = tf.keras

In [17]:
dataset = pd.read_csv(path, sep=',')
dataset

Unnamed: 0                                               text  sentiment
0              0  So there is no way for me to plug it in here i...          0
1              1                         Good case Excellent value.          1
2              2                             Great for the jawbone.          1
3              3  Tied to charger for conversations lasting more...          0
4              4                                  The mic is great.          1
...          ...                                                ...        ...
1987        1987  I think food should have flavor and texture an...          0
1988        1988                           Appetite instantly gone.          0
1989        1989  Overall I was not impressed and would not go b...          0
1990        1990  The whole experience was underwhelming and I t...          0
1991        1991  Then as if I hadn't wasted enough of my life t...          0

[1992 rows x 3 columns]

In [19]:
reviews = dataset['text']
reviews[:10].tolist()

['So there is no way for me to plug it in here in the US unless I go by a converter.',
 'Good case Excellent value.',
 'Great for the jawbone.',
 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!',
 'The mic is great.',
 'I have to jiggle the plug to get it to line up right to get decent volume.',
 'If you have several dozen or several hundred contacts then imagine the fun of sending each of them one by one.',
 'If you are Razr owner...you must have this!',
 'Needless to say I wasted my money.',
 'What a waste of money and time!.']

In [ ]:
tokenizer = Tokenizer(oov_token='<OOV>')
tokenizer.fit_on_texts(reviews)
word_index = tokenizer.word_index
print(len(word_index))
print(word_index.items())

In [29]:
sequences = tokenizer.texts_to_sequences(reviews)
padded_sequences = pad_sequences(sequences, padding='post', maxlen=25)

print(padded_sequences.shape)
print(reviews[0])
print(padded_sequences[0])

(1992, 25)
So there is no way for me to plug it in here in the US unless I go by a converter.
[  28   59    8   56  142   13   61    7  269    6   15   46   15    2
  149  449    4   60  113    5 1429    0    0    0    0]


In [67]:
sentences =  dataset['text'].to_list()
labels =  dataset['sentiment'].to_list()

training_size = int(len(sentences) * 0.8)

training_sent = sentences[:training_size]
testing_sent = sentences[training_size:]
training_lbl = np.array(labels[:training_size])
testing_lbl = np.array(labels[training_size:])
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

In [57]:
vocab_size = 1000
embedding_dim =16
max_lenght = 100
trunc_type = 'post'
padding_type = 'post'
OOV_tok = '<OOV>'

tokenizer = Tokenizer(num_words=vocab_size, oov_token=OOV_tok)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
seq = tokenizer.texts_to_sequences(training_sent)
padded = pad_sequences(seq, maxlen=max_lenght, padding=padding_type, truncating=trunc_type)

test_seq = tokenizer.texts_to_sequences(testing_sent)
test_padded  = pad_sequences(test_seq, maxlen=max_lenght, padding=padding_type, truncating=trunc_type)

In [ ]:
word_index

In [58]:
reverse_word_index = dict([value, key] for (key, value) in word_index.items())
def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

print(decode_review(padded_sequences[1]))
print(training_sent[1])

good case excellent value ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
Good case Excellent value.


In [68]:
model = tf.keras.models.Sequential([
    keras.layers.Embedding(vocab_size, embedding_dim, input_length = max_lenght),
    keras.layers.Flatten(),
    keras.layers.Dense(6, activation = 'relu'),
    keras.layers.Dense(1, activation = 'sigmoid'),
])

model.compile(loss=keras.losses.BinaryCrossentropy(), optimizer=keras.optimizers.Adam(), metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 100, 16)           16000     
                                                                 
 flatten_4 (Flatten)         (None, 1600)              0         
                                                                 
 dense_8 (Dense)             (None, 6)                 9606      
                                                                 
 dense_9 (Dense)             (None, 1)                 7         
                                                                 
Total params: 25,613
Trainable params: 25,613
Non-trainable params: 0
_________________________________________________________________


In [71]:
padded.shape, training_lbl.shape, test_padded.shape

((1593, 100), (1593,), (399, 100))

In [72]:
num_epochs = 32
model.fit(padded, training_lbl, epochs=num_epochs, validation_data=(test_padded, testing_lbl))

Epoch 1/32
50/50 [==============================] - 1s 7ms/step - loss: 0.6934 - accuracy: 0.5286 - val_loss: 0.6927 - val_accuracy: 0.5764
Epoch 2/32
50/50 [==============================] - 0s 2ms/step - loss: 0.6873 - accuracy: 0.5480 - val_loss: 0.7031 - val_accuracy: 0.4110
Epoch 3/32
50/50 [==============================] - 0s 2ms/step - loss: 0.6750 - accuracy: 0.5430 - val_loss: 0.6915 - val_accuracy: 0.4561
Epoch 4/32
50/50 [==============================] - 0s 2ms/step - loss: 0.6466 - accuracy: 0.6259 - val_loss: 0.6729 - val_accuracy: 0.5363
Epoch 5/32
50/50 [==============================] - 0s 2ms/step - loss: 0.5785 - accuracy: 0.8261 - val_loss: 0.6068 - val_accuracy: 0.7469
Epoch 6/32
50/50 [==============================] - 0s 2ms/step - loss: 0.4747 - accuracy: 0.8908 - val_loss: 0.5367 - val_accuracy: 0.7519
Epoch 7/32
50/50 [==============================] - 0s 2ms/step - loss: 0.3732 - accuracy: 0.9190 - val_loss: 0.5120 - val_accuracy: 0.7644
Epoch 8/32
50/50 [==